### ISSUE TITLE
why does the diagonal of covariance and Fisher matrix Have some negative numbers?

### ISSUE THREAD

**Issue by 1742479196** [CosmoStatGW/gwfast#1]

**Comment by FrancescoIacovelli** [comment]
Hi! I am very sorry for the late reply. 

This is something that never occurred to us, and should not be possible by construction for the Fisher. Could you please provide a configuration in which the issue shows up (event parameters, ASD, detectors, waveform, minimum and maximum frequency,… everything needed), as well as the options passed to the various functions (e.g., the inversion method used) so that we can try to reproduce and understand the problem?

Best regards,

Francesco & Michele

**Comment by 1742479196** [comment]
I'm sorry. I made a small mistake at that time (I forgot how to solve it now). I solved the problem in the afternoon after asking the question, but I'm not sure how to withdraw the problem. I'm sorry for the delay

**Comment by FrancescoIacovelli** [comment]
Ok, I am glad you managed to solve the problem and use our code! I will take care of closing the issue
